version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nightwatch
    versions:
    - 1.5.1
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: chalk
    versions:
    - 4.1.0
